name: test_r1_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - tqdm=4.65.0
  - pip
  - pip:
    - streamlit==1.28.1
    - plotly==5.15.0
    - loguru
    - packaging>=21.0
    - typing-extensions>=4.0.0
    - protobuf<4.0.0
    - pillow>=9.0.0
    - requests>=2.25.0 